name: Generate Contribution Snake

on:
  schedule:
    - cron: '0 */12 * * *'   # every 12 hours (change if you want)
  workflow_dispatch:         # allows manual runs

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Generate snake SVGs (svg-only)
        uses: Platane/snk/svg-only@v3
        id: snk
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit generated files
        uses: EndBug/add-and-commit@v9
        with:
          add: 'dist/**'
          message: 'chore: update contribution snake'
          default_author: github_actions
          push: true
